const products = [
    { 
        _id: '1',
        name: 'Airpods',
        image: '/images/airpods.jpg',
        description: 'Theese are aripods.',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    { 
        _id: '2',
        name: 'Alexa',
        image: '/images/alexa.jpg',
        description: 'This is alexa.',
        brand: 'Samsung',
        category: 'Electronics',
        price: 300.00,
        countInStock: 10,
        rating: 2.3,
        numReviews: 3,
    },
    { 
        _id: '3',
        name: 'Camera',
        image: '/images/camera.jpg',
        description: 'This is camera.',
        brand: 'Canon',
        category: 'Electronics',
        price: 360.00,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    { 
        _id: '4',
        name: 'Mouse',
        image: '/images/mouse.jpg',
        description: 'This is mouse.',
        brand: 'Aplle',
        category: 'Electronics',
        price: 7.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    { 
        _id: '5',
        name: 'Phone',
        image: '/images/phone.jpg',
        description: 'This is iphone.',
        brand: 'Aplle',
        category: 'Electronics',
        price: 640.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    { 
        _id: '6',
        name: 'Playstation',
        image: '/images/playstation.jpg',
        description: 'This is playstation.',
        brand: 'SONY',
        category: 'Electronics',
        price: 500.00,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    { 
        _id: '7',
        name: 'Sample',
        image: '/images/sample.jpg',
        description: 'This is sample.',
        brand: 'None',
        category: 'Electronics',
        price: 0,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
]

export default products